<?php

use App\Jobs\TodoboardJob;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::middleware(['is_install','switch_lang'])->group(function () {
    Auth::routes();
    Route::post('/dologin', 'Auth\LoginController@dologin')->name('login.custom');
    Route::redirect('/home', 'dashboard', 301)->name('home');
    Route::view('per', 'per');
    Route::post('test', 'TestController@test')->name('per.create');
/*Social Logins*/
    Route::get('login/{service}', 'Auth\LoginController@redirectToProvider')->name('social.login');
    Route::get('login/success/{service}/callback', 'Auth\LoginController@handleProviderCallback');

    // Front 
    Route::get('/', 'DashboardController@welcome')->name('home');
    Route::get('blog/detail/{id}', 'FrontController@blog_details')->name('blog.detail');
    Route::get('privacy-policy', 'FrontController@privacy_policy')->name('front-privacy-policy');
    Route::get('terms-and-condition', 'FrontController@terms_condition')->name('front-terms-condition');
    Route::post('register', 'Auth\RegisterController@register')->name('register');

/** Ajax Fetch State / City */
    Route::get('/choose-state', 'CityController@chooseState')->name('list.state');
    Route::get('/choose-city', 'CityController@chooseCity')->name('list.cities');
/** End */
    Route::group(['middleware' => ['super_admin']], function () {
        Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard.index');-
        Route::prefix('admin')->group(function () {
            Route::get('useraslogin/{id}', 'UsersController@login')->name('useraslogin');
            Route::get('settings', 'SettingController@get')->name('site.settings');
            Route::post('settings', 'SettingController@saveSettings')->name('site.settings.update');
            Route::get('mailsettings', 'SettingController@mailsetting')->name('mail.setting');
            Route::post('mailsettings', 'SettingController@savemailsetting')->name('mail.setting.save');
            Route::get('paymentsettings', 'SettingController@getpaymentsettings')->name('payment.settings');
            Route::post('paymentsettings', 'SettingController@savepaymentsettings')->name('payment.settings.save');
        });
        Route::prefix('manage')->group(function () {
            Route::get('blogs', function () {
                return view('admin.blog.create');
            });
            Route::resource('video', 'VideoController');
            Route::post('admin/video/status/{id}', 'VideoController@status_update')->name('video.status');
            Route::resource('level', 'LevelController');
            Route::post('admin/level/bulk_delete', 'LevelController@bulk_delete')->name('level.bulk_delete');
            Route::put('admin/level/change/{id}', 'LevelController@status_update')->name('level.status');
            Route::get('admin/manual-payment-settings', 'ManualPaymentGatewayController@getindex')->name('manual.payment.gateway');
            Route::post('admin/manual-payment-settings', 'ManualPaymentGatewayController@store')->name('manual.payment.gateway.store');
            Route::post('admin/manual-payment-settings-update/{id}', 'ManualPaymentGatewayController@update')->name('manual.payment.gateway.update');
            Route::post('admin/manual-payment-settings-delete/{id}', 'ManualPaymentGatewayController@delete')->name('manual.payment.gateway.delete');
            Route::put('admin/manual-payment-settings-change/{id}', 'ManualPaymentGatewayController@status_update')->name('manual.payment.gateway.status');
            Route::post('admin/manual-payment-settings-change/bulk_delete', 'ManualPaymentGatewayController@bulk_delete')->name('manual.payment.gateway.bulk_delete');
            Route::get('/pwa-settings', 'PWAController@index')->name('pwa.setting.index');
            Route::post('/pwa/update/setting', 'PWAController@updatesetting')->name('pwa.setting.update');
            Route::post('/pwa/update/icons/setting', 'PWAController@updateicons')->name('pwa.icons.update');
            Route::get('/viewall/filter/', 'EnquiryController@index')->name('filter');
            Route::get('user/image', 'UsersController@download')->name('user.image');
            Route::get('/user/filter/', 'UsersController@filter')->name('userfilter');
            Route::resource('memberattendance', 'MemberattendanceController');
            Route::post('admin/memberattendance/bulk_delete', 'MemberattendanceController@bulk_delete')->name('memberattendance.bulk_delete');
            Route::resource('staffattendance', 'StaffattendanceController');
            Route::post('admin/staffattendance/bulk_delete', 'StaffattendanceController@bulk_delete')->name('staffattendance.bulk_delete');
            Route::resource('profile', 'ProfileController');
            Route::resource('trainer', 'TrainerController');
            Route::post('admin/trainer/bulk_delete', 'TrainerController@bulk_delete')->name('trainer.bulk_delete');
            Route::put('admin/trainer/change/{id}', 'TrainerController@status_update')->name('trainer.status');
            Route::resource('trainerlist', 'TrainerlistController');
            Route::get('get-data-by-id', 'TrainerlistController@getData')->name('get.data.by.id');
            Route::post('admin/trainerlist/bulk_delete', 'TrainerlistController@bulk_delete')->name('trainerlist.bulk_delete');
            Route::put('admin/trainerlist/change/{id}', 'TrainerlistController@status_update')->name('trainerlist.status');
            Route::resource('goal', 'GoalController');
            Route::post('admin/goal/bulk_delete', 'GoalController@bulk_delete')->name('goal.bulk_delete');
            Route::put('admin/goal/change/{id}', 'GoalController@status_update')->name('goal.status');
            Route::resource('followup', 'FollowupController');
            Route::post('admin/followup/bulk_delete', 'FollowupController@bulk_delete')->name('followup.bulk_delete');
            Route::resource('ptsubscription', 'PtsubscriptionController');
            Route::post('admin/ptsubscription/bulk_delete', 'PtsubscriptionController@bulk_delete')->name('ptsubscription.bulk_delete');
            Route::resource('reminder', 'ReminderController');
            Route::post('admin/reminder/bulk_delete', 'ReminderController@bulk_delete')->name('reminder.bulk_delete');
            Route::resource('users', 'UsersController');
            Route::resource('roles', 'RolesController');
            Route::resource('/packages', 'PackagesController');
            Route::put('admin/packages/change/{id}', 'PackagesController@status_update')->name('packages.status');
            Route::post('admin/packages/bulk_delete', 'PackagesController@bulk_delete')->name('packages.bulk_delete');
            Route::get('admin/packages/destroy/{id}', 'PackagesController@destroy')->name('packages.destroy');
            Route::resource('/religion', 'ReligionController');
            Route::put('admin/religion/change/{id}', 'ReligionController@status_update')->name('religion.status');
            Route::post('admin/religion/bulk_delete', 'ReligionController@bulk_delete')->name('religion.bulk_delete');
            Route::resource('/secondlanguage', 'SecondlanguageController');
            Route::put('admin/secondlanguage/change/{id}', 'SecondlanguageController@status_update')->name('secondlanguage.status');
            Route::post('admin/secondlanguage/bulk_delete', 'SecondlanguageController@bulk_delete')->name('secondlanguage.bulk_delete');
            Route::resource('/quotation', 'QuotationController');
            Route::put('admin/quotation/change/{id}', 'QuotationController@status_update')->name('quotation.status');
            Route::post('admin/quotation/bulk_delete', 'QuotationController@bulk_delete')->name('quotation.bulk_delete');
            Route::post('admin/quotation/{id}', 'QuotationController@show_store')->name('quotation.show_store');
            Route::get('/downloadPDF/{id}', 'QuotationController@downloadPDF');
            Route::resource('/occupation', 'OccupationController');
            Route::put('admin/occupation/change/{id}', 'OccupationController@status_update')->name('occupation.status');
            Route::post('admin/occupation/bulk_delete', 'OccupationController@bulk_delete')->name('occupation.bulk_delete');
            Route::get('/recycle', 'RecycleController@index')->name('recycle.index');
            Route::resource('/cost', 'CostController');
            Route::put('admin/cost/change/{id}', 'CostController@status_update')->name('cost.status');
            Route::post('admin/cost/bulk_delete', 'CostController@bulk_delete')->name('cost.bulk_delete');
            Route::get('only-trashed', 'CostController@onlyTrashed');
            Route::get('restore/{id}', 'CostController@restore');
            Route::get('invoice', 'InvoiceController@get')->name('invoice.settings');
            Route::post('invoice', 'InvoiceController@saveSettings')->name('invoice.settings.update');
            Route::resource('/group', 'GroupController');
            Route::put('admin/group/change/{id}', 'GroupController@status_update')->name('group.status');
            Route::post('admin/group/bulk_delete', 'GroupController@bulk_delete')->name('group.bulk_delete');
            Route::resource('/quickaction', 'QuickactionController');
            Route::put('admin/quickaction/change/{id}', 'QuickactionController@status_update')->name('quickaction.status');
            Route::post('admin/quickaction/bulk_delete', 'QuickactionController@bulk_delete')->name('quickaction.bulk_delete');
            Route::resource('/appsetting', 'AppsettingController');
            Route::put('admin/appsetting/change/{id}', 'AppsettingController@status_update')->name('appsetting.status');
            Route::post('admin/appsetting/bulk_delete', 'AppsettingController@bulk_delete')->name('appsetting.bulk_delete');
            Route::resource('/onboarding', 'OnboardingController');
            Route::put('admin/onboarding/change/{id}', 'OnboardingController@status_update')->name('onboarding.status');
            Route::post('admin/onboarding/bulk_delete', 'OnboardingController@bulk_delete')->name('onboarding.bulk_delete');
            Route::resource('fees', 'FeesController');
            Route::put('admin/fees/change/{id}', 'FeesController@status_update')->name('fees.status');
            Route::post('admin/fees/bulk_delete', 'FeesController@bulk_delete')->name('fees.bulk_delete');
            Route::resource('exercise', 'ExerciseController');
            Route::post('admin/exercise/bulk_delete', 'ExerciseController@bulk_delete')->name('exercise.bulk_delete');
            Route::resource('exercisepackage', 'ExercisepackageController');
            Route::post('admin/exercisepackage/bulk_delete', 'ExercisepackageController@bulk_delete')->name('exercisepackage.bulk_delete');
            Route::put('admin/exercisepackage/change/{id}', 'ExercisepackageController@status_update')->name('exercisepackage.status');
            Route::resource('supplement', 'SupplementController');
            Route::put('admin/supplement/change/{id}', 'SupplementController@status_update')->name('supplement.status');
            Route::post('admin/supplement/bulk_delete', 'SupplementController@bulk_delete')->name('supplement.bulk_delete');
            Route::resource('todo', 'TodoController');
            Route::put('admin/Todo/change/{id}', 'TodoController@status_update')->name('todo.status');
            Route::post('admin/todo/bulk_delete', 'TodoController@bulk_delete')->name('todo.bulk_delete');
            Route::resource('trainerpackages', 'TrainerpackagesController');
            Route::put('admin/Trainerpackages/change/{id}', 'TrainerpackagesController@status_update')->name('trainerpackages.status');
            Route::post('admin/trainerpackages/bulk_delete', 'TrainerpackagesController@bulk_delete')->name('trainerpackages.bulk_delete');
            Route::resource('/language', 'LanguageController');
            Route::get('language-switch/{local}', 'LanguageSwitchController@languageSwitch')->name('languageSwitch');
        });
        Route::get('restore/{id}', 'RecycleController@restore')->name('restore');
        Route::resource('diet', 'DietController');
        Route::post('admin/diet/bulk_delete', 'DietController@bulk_delete')->name('diet.bulk_delete');
        Route::put('admin/diet/change/{id}', 'DietController@status_update')->name('diet.status');
        Route::resource('measurement', 'MeasurementController');
        Route::post('admin/measurement/bulk_delete', 'MeasurementController@bulk_delete')->name('measurement.bulk_delete');
        Route::put('admin/measurement/change/{id}', 'MeasurementController@status_update')->name('measurement.status');
        Route::put('admin/exercise/change/{id}', 'ExerciseController@status_update')->name('exercise.status');
        Route::resource('locker', 'LockerController');
        Route::put('admin/locker/change/{id}', 'LockerController@status_update')->name('locker.status');
        Route::post('admin/locker/bulk_delete', 'LockerController@bulk_delete')->name('locker.bulk_delete');
    });
    Route::resource('multicurrency', 'MultiCurrencyController');
    Route::post('multicurrency/update/currency', 'MultiCurrencyController@auto_update_currency')->name('auto.update.rates');
    Route::put('multicurrency/default_currency/{id}', 'MultiCurrencyController@default')->name('multicurrency.default');
    Route::resource('ptsubscripition', 'PtsubscriptionController');
    Route::put('admin/ptsubscripition/change/{id}', 'PtsubscriptionController@status_update')->name('ptsubscripition.status');
    Route::post('admin/ptsubscripition/bulk_delete', 'PtsubscriptionController@bulk_delete')->name('ptsubscripition.bulk_delete');
    Route::prefix('manage')->group(function () {
        Route::group(['middleware' => ['auth']], function () {
            Route::resource('admin/faq', 'FaqController');
            Route::post('admin/faq/status/{id}', 'FaqController@status_update')->name('faq.status');
            Route::post('admin/faq/bulk_delete', 'FaqController@bulk_delete')->name('faq.bulk_delete');
            Route::resource('admin/pages', 'PagesController');

            Route::get('privacy-policy', 'PagesController@privacy_policy')->name('privacy-policy');
            Route::get('terms-condition', 'PagesController@terms_condition')->name('terms-condition');
            Route::post('privacy-policy-update', 'PagesController@privacy_policy_update')->name('privacy-policy-update');
            Route::post('terms-condition-update', 'PagesController@terms_condition_update')->name('term-condition-update');

            Route::post('admin/pages/status/{id}', 'PagesController@status_update')->name('pages.status');
            Route::post('admin/pages/bulk_delete', 'PagesController@bulk_delete')->name('pages.bulk_delete');
            Route::resource('admin/selectpages', 'SelectPagesController');
            Route::post('admin/selectpages/status/{id}', 'SelectPagesController@status_update')->name('selectpages.status');
            Route::post('admin/selectpages/bulk_delete', 'SelectPagesController@bulk_delete')->name('selectpages.bulk_delete');
            Route::resource('admin/appointment', 'AppointmentController');
            Route::post('admin/appointment/status/{id}', 'AppointmentController@status_update')->name('appointment.status');
            Route::post('admin/appointment/bulk_delete', 'AppointmentController@bulk_delete')->name('appointment.bulk_delete');
            Route::resource('admin/appointmentsetting', 'AppointmentsettingController');
            Route::post('admin/appointmentsetting/status/{id}', 'AppointmentsettingController@status_update')->name('appointmentsetting.status');
            Route::post('admin/appointmentsetting/bulk_delete', 'AppointmentsettingController@bulk_delete')->name('appointmentsetting.bulk_delete');
            Route::resource('type', 'TypeController');
            Route::put('admin/Type/change/{id}', 'TypeController@status_update')->name('type.status');
            Route::post('admin/type/bulk_delete', 'TypeController@bulk_delete')->name('type.bulk_delete');
            Route::resource('exercisename', 'ExercisenameController');
            Route::put('admin/exercisename/change/{id}', 'ExercisenameController@status_update')->name('exercisename.status');
            Route::post('admin/exercisename/bulk_delete', 'ExercisenameController@bulk_delete')->name('exercisename.bulk_delete');
            Route::resource('workoutplan', 'WorkoutplanController');
            Route::put('admin/workoutplan/change/{id}', 'WorkoutplanController@status_update')->name('workoutplan.status');
            Route::post('admin/workoutplan/bulk_delete', 'WorkoutplanController@bulk_delete')->name('workoutplan.bulk_delete');
            Route::resource('day', 'DayController');
            Route::put('admin/day/change/{id}', 'DayController@status_update')->name('day.status');
            Route::post('admin/day/bulk_delete', 'DayController@bulk_delete')->name('day.bulk_delete');
            Route::resource('service', 'ServiceController');
            Route::post('admin/service/bulk_delete', 'ServiceController@bulk_delete')->name('service.bulk_delete');
            Route::put('admin/service/change/{id}', 'ServiceController@status_update')->name('service.status');
            Route::resource('dietid', 'DietidController');
            Route::post('admin/dietid/bulk_delete', 'DietidController@bulk_delete')->name('dietid.bulk_delete');
            Route::put('admin/dietid/change/{id}', 'DietidController@status_update')->name('dietid.status');
            Route::resource('dietpackage', 'DietpackageController');
            Route::post('admin/dietpackage/bulk_delete', 'DietpackageController@bulk_delete')->name('dietpackage.bulk_delete');
            Route::put('admin/dietpackage/change/{id}', 'DietpackageController@status_update')->name('dietpackage.status');
            Route::resource('dietcontent', 'DietContentController');
            Route::post('admin/dietcontent/bulk_delete', 'DietContentController@bulk_delete')->name('dietcontent.bulk_delete');
            Route::put('admin/dietcontent/change/{id}', 'DietContentController@status_update')->name('dietcontent.status');
            Route::get('/diet/fetch/search', 'DietController@fetch')->name('diet.fetch');
            Route::resource('enquiry', 'EnquiryController');
            Route::post('admin/enquiry/bulk_delete', 'EnquiryController@bulk_delete')->name('enquiry.bulk_delete');
            Route::get('admin/enquiry/demo', 'EnquiryController@demo')->name('demo');
            Route::get('admin/enquiry/join', 'EnquiryController@join')->name('join');
            Route::resource('enquiryhealth', 'EnquiryHealthController');
            Route::post('admin/enquiryhealth/bulk_delete', 'EnquiryHealthController@bulk_delete')->name('enquiryhealth.bulk_delete');
            Route::put('admin/enquiryhealth/change/{id}', 'EnquiryHealthController@status_update')->name('enquiryhealth.status');
            Route::get('admin/enquiry/{id}', 'EnquiryController@show')->name('enquiry.show');
            Route::resource('admin/blog', 'BlogController');
            Route::post('admin/blog/status/{id}', 'BlogController@status_update')->name('blog.status');
            Route::resource('admin/blogcategory', 'BlogCategoryController');
            Route::post('admin/blogcategory/status/{id}', 'BlogCategoryController@status_update')->name('blogcategory.status');
            Route::post('admin/blogcategory/bulk_delete', 'BlogCategoryController@bulk_delete')->name('blogcategory.bulk_delete');
            Route::resource('admin/slider', 'SliderController');
            Route::post('admin/slider/status/{id}', 'SliderController@status_update')->name('slider.status');
            Route::post('admin/slider/bulk_delete', 'SliderController@bulk_delete')->name('slider.bulk_delete');
            Route::get('blogs', 'BlogController@blog');
            Route::get('blog/{slug}', 'BlogController@blogdetail');
        });
    });
    Route::get('my-store', 'razorpay\PaymentController@show_products');
    Route::get('pay/success', 'razorpay\PaymentController@pay_success')->name('paysuccess');
    Route::post('thank-you', 'razorpay\PaymentController@thank_you');
    Route::get('history', 'razorpay\PaymentController@show')->name('history');
    Route::post('payment/status', 'EventController@paymentCallback');
    Route::get('event', 'EventController@bookEvent');
    Route::post('payment', 'EventController@eventOrderGen');
    Route::post('/save/twillo/settings', 'TwilloController@savesettings')->name('change.twilo.settings');
    Route::post('/sendsms', 'TwilloController@sendsms');
    Route::post('/change/msg/channel', 'TwilloController@changechannel')->name('change.channel');
    Route::get('/admin/sms/settings', 'Msg91Controller@getSettings')->name('sms.settings');
    Route::post('/admin/sms/settings', 'Msg91Controller@updateSettings')->name('sms.update.settings');
    Route::get('/device-logs', 'DeviceController@index')->name('device.logs');
    Route::group(['middleware' => ['auth']], function () {
        Route::get('admin/setting/general', 'SettingController@general');
        Route::post('admin/setting/store', 'SettingController@store')->name('setting.store');
        Route::post('admin/setting/general_update+', 'SettingController@general_update')->name('setting.general_update');
        Route::get('admin/setting/other', 'SettingController@other');
        Route::post('admin/setting/other_update', 'SettingController@other_update')->name('other.update');
        Route::get('admin/setting/footer', 'SettingController@footer');
        Route::post('admin/setting/footer_update', 'SettingController@footer_update')->name('footer.update');
        Route::get('admin/setting/seo', 'SettingController@seo');
        Route::post('admin/setting/seo_update', 'SettingController@seo_update')->name('seo.update');
        Route::get('admin/setting/bank', 'SettingController@bank');
        Route::post('admin/setting/bank_update', 'SettingController@bank_update')->name('bank.update');
        Route::get('admin/setting/mail', 'ConfigController@mail');
        Route::post('admin/setting/mail_update', 'ConfigController@mail_update')->name('mail.update');
        Route::get('admin/setting/api', 'ConfigController@api');
        Route::post('admin/setting/api_update', 'ConfigController@api_update')->name('api.update');
        Route::get('admin/setting/sociallogin', 'ConfigController@sociallogin');
        Route::post('admin/setting/sociallogin_update', 'ConfigController@sociallogin_update')->name('sociallogin.update');
        Route::resource('admin/setting/social', 'SocialController');
        Route::post('admin/setting/social/status/{id}', 'SocialController@status_update')->name('social.status');
        Route::get('/under-construction', 'ConstructionController@index')->name('construction.index');
        Route::get('/under-construction', 'ConstructionController@index')->name('construction.index');
    });
    Route::get('/verify', function () {
        return view('auth.verify');
    })->name('verify');
    Route::post('/verify', 'Auth\ApiAuthController@verify')->name('verify');
    Route::resource('admin/todo', 'TodoController');
    Route::resource('admin/todoboard', 'TodoBoardController');
    Route::post('admin/todo/status/{id}', 'TodoController@status_update')->name('todo.status');
    Route::post('admin/todo/bulk_delete', 'TodoController@bulk_delete')->name('todo.bulk_delete');
    Route::get('admin/todoboard/list/{id}', 'TodoBoardController@all_todos');
    Route::post('store/todo-card', 'TodoCardController@store')->name('todocard.store');
    Route::post('update/todo-card/', 'TodoCardController@update')->name('todocard.update');
    Route::delete('delete/todo-card/', 'TodoCardController@delete')->name('todocard.delete');
    Route::get('getsecretkey', 'GenerateApiController@getkey')->name('get.api.key');
    Route::post('createkey', 'GenerateApiController@createKey')->name('apikey.create');
    Route::resource('affilates', 'AffilatesController');
    Route::get('affilates', 'AffilatesController@get')->name('save.affilates');
    Route::post('affilates', 'AffilatesController@saveAffilates')->name('save.affilates.update');
    Route::get('/user/affiliate/settings', 'AffilatesController@userdashboard')->name('user.affiliate.settings');
    Route::get('/reports', 'AffilatesController@reports')->name('reports');
    Route::get('/admin/addon-manger', 'AddOnManagerController@index')->name('addonmanger.index');
    Route::post('/admin/toggle/module', 'AddOnManagerController@toggle');
    Route::post('/admin/addon/install', 'AddOnManagerController@install')->name('addon.install');
    Route::post('/admin/addon/delete', 'AddOnManagerController@delete')->name('addon.delete');
    Route::get('notifications', 'NotificationController@markAsRead')
        ->name('markAsRead');
    Route::post('/admin/one-signal/keys', 'NotificationController@updateKeys')->name('admin.onesignal.keys');
    Route::get('/admin/push-notifications', 'NotificationController@index')->name('admin.push.noti.settings');
    Route::post('/admin/push-notifications', 'NotificationController@push')->name('admin.push.notif');
    Route::get('delete/notifications', 'NotificationController@delete')
        ->name('deleteNotification');
    Route::get('/clear-cache', function () {
        \Artisan::call('cache:clear');
        \Artisan::call('view:cache');
        \Artisan::call('view:clear');
        toastr()->success("Cache has been cleared !");
        return back();
    });
    Route::get('test/locker', 'LockController@index')->name('locker.locker');
    Route::get('/testjob', function () {
        TodoboardJob::dispatch();
    });
});
